import type { Metadata } from "next";
import "./globals.css";
import { AuthProvider } from "@/app/context/authcontext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="projecthyperpink">
      <body className="bg-base-200">
        <AuthProvider>{children}</AuthProvider>
      </body>
    </html>
  );
}
